### ISSUE TITLE
Does it work with bigip 10.x ?

### ISSUE THREAD

**Issue by silou** [sschneid/perl-bigip-parseconfig#2]
Hello,

Does it work with bigip v10.x ?

I can't get the member with a v10 config file.

Ex:

Perl Code : 

print Dumper($bigipbe->pool('pool1'));
print Dumper($bigipbe->pool('pool2'));
print Dumper($bigipbe->pool('pool3'));
# ----------

Result:

$VAR1 = { 
          'members' => '127.0.0.1:http {}',
          'monitor' => 'all monitor1'
        };
$VAR1 = { 
          'members' => '{',
          'monitor' => 'all monitor2'
        };
$VAR1 = { 
          'members' => '{',
          'monitor' => 'all monitor3'
        };
# ----------------

**Comment by sschneid** [comment]
I don't think so, or at least I would assume not based on your message.  I've changed employers and no longer have access to any F5 equipment.  :(

You are welcome to fork or take over this project!
